### ISSUE TITLE
Crash every time I use Morph mod

### ISSUE THREAD

**Issue by Drock1994** [Funwayguy/InfiniteInvo#11]
Hi I added infinite inventory to a new mod pack i a making and every time I use the morph mod the game allows me to morph but then locks up and crashes.  I can log back in and everything is alright until I morph again.  The crash log states net.minecraft.entity.player.InventoryPlayer cannot be cast to infiniteinvo.inventory.BigInventoryPlayer. 

Here is the crash log: http://pastebin.com/Q4J0UYbf

**Comment by Funwayguy** [comment]
Fixed for next update

**Comment by Drock1994** [comment]
Thank you very much...awesome mod
