### ISSUE TITLE
Custom slots not clearing color when drawn.

### ISSUE THREAD

**Issue by kirderf1** [Funwayguy/InfiniteInvo#12]
When used for a container with for example buttons, the GL color is left as the color of the string of the previous button. Thus drawing the slots in an other color. This can be easily solved by calling GL11.glColor4f(1.0F, 1.0F, 1.0F, 1.0F); before drawing stuff in the InvoScrollBar class.

**Comment by Funwayguy** [comment]
Thanks for finding this, especially pointing out exactly where I messed up. I credited you in the changelog
