### ISSUE TITLE
A compability improvement

### ISSUE THREAD

**Issue by kirderf1** [Funwayguy/InfiniteInvo#14]
When a container creates and adds the toolbar slots before the rest of the inventory, the mod mistakes that row as the first row of the main inventory when sending the content to the client side. I'll see if I can find the source of the problem after checking for other possible compability issues with the mod I'm working with.

**Comment by kirderf1** [comment]
Hmm. In InvoPacket.HandleServer.onMessage() where the id is 2, it handles the first 27 inventory slots from the container, without checking if the slots refer to the toolbar or the rest of the inventory.
I haven't looked into much on what is supposed to do what, but the most ideal solution would be to make the if statement (that checks inventory and "origIndex") also check if the slot index is larger than 9.

**Comment by Funwayguy** [comment]
I knew I stuffed up the indexes somewhere... thanks for pointing that out. I should have a fix out for that soon.

**Comment by Funwayguy** [comment]
I think I've fixed this for the next update
