### ISSUE TITLE
Creative inventory not woking correctly

### ISSUE THREAD

**Issue by kirderf1** [Funwayguy/InfiniteInvo#15]
You probably know of this issue already, but see this as a reminder then. The mod doesn't handle the survival inventory (the one accessed from the creative inventory gui) correctly.

**Comment by Funwayguy** [comment]
Actually I specifically disabled InfiniteInvo interaction with that UI because it causes some weird side effects I can't find the cause of yet and also I didn't want creative player's inventory spaces being locked out.

**Comment by Funwayguy** [comment]
Never mind about my comment above. I went and tested it and I see the problem.

**Comment by Funwayguy** [comment]
Got this fixed for next release after throwing a ton of code at the creative menu trying to get it to work.
