### ISSUE TITLE
Duplicate block when using pick-block in creative

### ISSUE THREAD

**Issue by kirderf1** [Funwayguy/InfiniteInvo#16]
This issue seem to only be applied when the maximum size is more than the normal size of 27. What happens is that the block picked is placed in the hotbar on the client side as it should, but then that item is on the server side instead placed on the slot increased with [maximum inventory size] - 27, so that if the maximum inventory size is 28, the item will be placed  one slot to the right compared to the client side. And an inventory with size 30 the server side item will be placed three slots to the right. This issue doesn't seem to apply when the max size is less than 27 though.

**Comment by Funwayguy** [comment]
I believe this is related to the indexing problem you specified earlier so I will fix that one and see if it indirectly fixes this too.
