### ISSUE TITLE
Unlocking Spaces with EXP then relogging resets the spaces (running local Server)

### ISSUE THREAD

**Issue by Reclaimer52** [Funwayguy/InfiniteInvo#17]
I've had an issue with the spaces i have unlocked 5 slots and now only have one unlocked while others who have unlocked 1 space have more or less depending on who's logged in.  it seems to change every time someone logs in or out.

The xp bar reset's as well although it wont let me re-buy the slots i have already bought. however if i were to say buy the 6th slot i would get all of them back. If you need more info let me know.

**Comment by Reclaimer52** [comment]
we also found that the stuff that is in the slots when it re locks is still there just inaccessable

**Comment by Funwayguy** [comment]
I think I've fixed this for the next update.
