### ISSUE TITLE
Inventory pretty much unusable/buggy

### ISSUE THREAD

**Issue by bokeustermans** [Funwayguy/InfiniteInvo#20]
I'm using the Resonant rise mainline pack and wanted to add your mod to it, upon adding it the inventory expanded as expected, but caused me to be unable to access the TiCo and Galacticraft tabs, Baubles remained accessible. 
Is this a known issue or is it because of incompatibility with other mods?
I would REALLY like to use your mod

**Comment by Funwayguy** [comment]
I know these were working before with InfiniteInvo just fine in the last version. No idea how they broke though

**Comment by bokeustermans** [comment]
I'm doing some testing to see what it might be, I'll post pics/info

**Comment by bokeustermans** [comment]
When turning the compability mode on the inventory becomes partly unusable unless I'm in a different tab. It's very strange

**Comment by theaigcaman** [comment]
![2015-02-19_23 07 07](https://cloud.githubusercontent.com/assets/11086304/6282124/6cac4300-b88c-11e4-8e6a-777828b20c14.png)
i get this problem does anybody know how to fix it?

**Comment by theaigcaman** [comment]
BTW, i'm on resonant rise excessive and the hotbar is the pickaxe and sword and such, it works just fine when i don't add rows, but i would like to

**Comment by Funwayguy** [comment]
Oh wow that is really badly broken. I'll take a look at it today and see what I can do but I make no guarantees, this mod has been breaking in so many weird ways in relation to syncing IDs and positions.

**Comment by Funwayguy** [comment]
Is this still occurring as of the last version?

**Comment by bokeustermans** [comment]
It sort of works, yes. The inventory is usable, but even in a quick 2 minute test I found being unable to use inventories (chests) as the items would disappear even if I shift clicked them into my inventory, could be mod interaction bug with mouse tweaks.

**Comment by Funwayguy** [comment]
I might run some tests with MouseTweaks as it might play a part in the shift clicking/dragging issue

**Comment by bokeustermans** [comment]
Even just clicking an item or pressing q to drop it doesn't work while it is in the chest

**Comment by Funwayguy** [comment]
Just double checked this issue again using MouseTweaks, ITweaks and NEI with build 1.0.35 and everything seems to be in working order.
