### ISSUE TITLE
Crash in single player

### ISSUE THREAD

**Issue by Badcholo** [Funwayguy/InfiniteInvo#21]
i selected the tab under to unlock a slot. After unlocking. I had set the config to use vanilla inventory.
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2/14/15 6:24 AM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: -1
	at net.minecraft.client.gui.achievement.GuiStats$StatsItem.<init>(SourceFile:435)
	at net.minecraft.client.gui.achievement.GuiStats.func_146509_g(SourceFile:120)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147293_a(NetHandlerPlayClient.java:1322)
	at net.minecraft.network.play.server.S37PacketStatistics.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S37PacketStatistics.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.gui.achievement.GuiStats$StatsItem.<init>(SourceFile:435)
	at net.minecraft.client.gui.achievement.GuiStats.func_146509_g(SourceFile:120)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147293_a(NetHandlerPlayClient.java:1322)
	at net.minecraft.network.play.server.S37PacketStatistics.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S37PacketStatistics.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Badcholo'/345, l='MpServer', x=-822.22, y=81.62, z=353.63]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-827,64,338), Chunk: (at 5,4,2 in -52,21; contains blocks -832,0,336 to -817,255,351), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 8277 game time, 8277 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 88 total; [Entity_SpecialCreeper['Creeper'/1763, l='MpServer', x=-796.73, y=31.46, z=381.79], Entity_SpecialZombie['Zombie'/1762, l='MpServer', x=-791.50, y=33.00, z=371.44], EntityBat['Bat'/1216, l='MpServer', x=-745.72, y=32.10, z=336.75], EntityChicken['Chicken'/129, l='MpServer', x=-841.44, y=81.00, z=323.53], EntityChicken['Chicken'/128, l='MpServer', x=-838.53, y=80.00, z=314.63], Entity_SpecialZombie['Zombie'/131, l='MpServer', x=-844.91, y=24.00, z=350.72], EntityChicken['Chicken'/130, l='MpServer', x=-831.56, y=83.00, z=328.59], EntityBat['Bat'/1909, l='MpServer', x=-776.55, y=14.64, z=422.46], EntityGiantZombie['Giant Zombie'/1479, l='MpServer', x=-890.00, y=23.00, z=412.44], EntityFish['Fish'/152, l='MpServer', x=-816.77, y=60.69, z=378.55], EntitySplittingCreeper['Splitting Creeper'/1779, l='MpServer', x=-858.50, y=29.00, z=371.50], EntityBat['Bat'/1658, l='MpServer', x=-762.81, y=20.71, z=340.65], EntityFish['Fish'/154, l='MpServer', x=-818.22, y=59.81, z=385.06], EntityFireSkeleton['Fire Skeleton'/1112, l='MpServer', x=-772.50, y=21.00, z=367.50], EntityDeathCreeper['Death Creeper'/1348, l='MpServer', x=-755.50, y=71.00, z=326.50], EntityWitch['Witch'/2029, l='MpServer', x=-851.50, y=17.00, z=401.50], EntityDrowningCreeper['Drowning Creeper'/1347, l='MpServer', x=-899.50, y=23.00, z=399.50], EntityWitch['Witch'/2030, l='MpServer', x=-852.50, y=17.00, z=400.50], EntityChicken['Chicken'/151, l='MpServer', x=-823.53, y=82.00, z=316.53], EntityCow['Cow'/171, l='MpServer', x=-797.38, y=66.00, z=379.50], EntityFish['Fish'/169, l='MpServer', x=-819.94, y=60.56, z=377.93], EntityFish['Fish'/168, l='MpServer', x=-803.74, y=60.69, z=370.70], EntitySniperSkeleton['Sniper Skeleton'/2103, l='MpServer', x=-791.09, y=47.00, z=348.50], EntityDarkCreeper['Dark Creeper'/2006, l='MpServer', x=-765.50, y=40.00, z=275.50], EntityCow['Cow'/174, l='MpServer', x=-800.06, y=66.00, z=385.47], EntityCow['Cow'/173, l='MpServer', x=-798.81, y=65.00, z=387.78], EntityJumpingCreeper['Jumping Creeper'/2005, l='MpServer', x=-765.50, y=40.00, z=279.50], EntityCow['Cow'/172, l='MpServer', x=-810.06, y=69.00, z=387.03], EntityGiantSkeleton['Giant Skeleton'/2104, l='MpServer', x=-787.52, y=46.00, z=349.53], EntitySquid['Squid'/167, l='MpServer', x=-807.66, y=56.38, z=370.56], EntityFish['Fish'/166, l='MpServer', x=-809.53, y=60.00, z=370.69], EntitySquid['Squid'/165, l='MpServer', x=-811.50, y=56.00, z=376.50], EntityFish['Fish'/164, l='MpServer', x=-801.22, y=61.88, z=368.63], EntityArmorCreeper['Armor Creeper'/1867, l='MpServer', x=-752.50, y=50.00, z=310.50], EntityDrowningCreeper['Drowning Creeper'/1627, l='MpServer', x=-840.50, y=25.00, z=358.50], EntitySquid['Squid'/184, l='MpServer', x=-796.28, y=58.34, z=358.84], EntityDarkCreeper['Dark Creeper'/1626, l='MpServer', x=-838.50, y=25.00, z=358.50], EntitySquid['Squid'/185, l='MpServer', x=-795.50, y=57.00, z=359.50], EntityCow['Cow'/190, l='MpServer', x=-788.47, y=69.00, z=416.09], EntityDirtCreeper['Dirt Creeper'/1868, l='MpServer', x=-752.50, y=50.00, z=311.50], EntityCow['Cow'/188, l='MpServer', x=-784.50, y=68.00, z=416.50], EntityBat['Bat'/905, l='MpServer', x=-777.94, y=14.10, z=406.50], EntityCow['Cow'/189, l='MpServer', x=-786.50, y=68.00, z=418.50], EntityMoth['Moth'/903, l='MpServer', x=-756.76, y=17.93, z=404.38], EntityCricket['Cricket'/900, l='MpServer', x=-899.28, y=63.00, z=324.78], EntityEnderCreeper['Ender Creeper'/1513, l='MpServer', x=-757.91, y=34.00, z=380.38], EntityBat['Bat'/182, l='MpServer', x=-790.25, y=37.10, z=366.25], EntityBat['Bat'/898, l='MpServer', x=-759.49, y=27.77, z=280.82], EntitySquid['Squid'/183, l='MpServer', x=-795.50, y=59.31, z=361.22], EntityCow['Cow'/205, l='MpServer', x=-768.78, y=68.00, z=432.50], EntityCow['Cow'/204, l='MpServer', x=-762.31, y=72.00, z=432.47], EntityTropiFish['Tropical Fish'/1424, l='MpServer', x=-878.16, y=61.14, z=300.90], EntitySplittingCreeper['Splitting Creeper'/1034, l='MpServer', x=-787.50, y=70.00, z=329.50], EntitySniperSkeleton['Sniper Skeleton'/1018, l='MpServer', x=-751.41, y=20.00, z=412.16], EntityTropiFish['Tropical Fish'/1425, l='MpServer', x=-869.16, y=61.01, z=304.91], EntityBrutishZombie['Brutish Zombie'/1968, l='MpServer', x=-837.53, y=18.00, z=377.03], EntitySpitfireSkeleton['Spitfire Skeleton'/1020, l='MpServer', x=-754.81, y=19.00, z=406.72], Entity_SpecialZombie['Zombie'/201, l='MpServer', x=-770.50, y=29.00, z=303.50], Entity_SpecialZombie['Zombie'/1969, l='MpServer', x=-840.31, y=16.00, z=380.53], EntityMiniCreeper['Mini Creeper'/1022, l='MpServer', x=-774.50, y=26.00, z=373.50], EntityCow['Cow'/203, l='MpServer', x=-781.53, y=70.00, z=409.69], Entity_SpecialSpider['Spider'/1023, l='MpServer', x=-787.94, y=21.00, z=377.19], EntityPlagueZombie['Plague Zombie'/202, l='MpServer', x=-768.50, y=21.00, z=341.50], Entity_SpecialZombie['Zombie'/2141, l='MpServer', x=-813.50, y=22.00, z=395.50], EntityFishingZombie['Fishing Zombie'/2140, l='MpServer', x=-814.50, y=22.00, z=396.50], EntityGiantZombie['Giant Zombie'/1982, l='MpServer', x=-802.50, y=28.00, z=395.50], EntitySniperSkeleton['Sniper Skeleton'/1027, l='MpServer', x=-880.88, y=14.00, z=337.56], EntityJumpingCreeper['Jumping Creeper'/2137, l='MpServer', x=-816.50, y=22.00, z=399.50], EntityClientPlayerMP['Badcholo'/345, l='MpServer', x=-822.22, y=81.62, z=353.63], EntityGiantZombie['Giant Zombie'/2139, l='MpServer', x=-815.50, y=22.00, z=398.50], EntityEnderCreeper['Ender Creeper'/2138, l='MpServer', x=-814.72, y=22.00, z=400.63], EntityPig['Pig'/216, l='MpServer', x=-754.59, y=74.00, z=279.06], EntityTropiFish['Tropical Fish'/217, l='MpServer', x=-750.80, y=60.88, z=386.83], EntityBat['Bat'/1413, l='MpServer', x=-899.49, y=12.00, z=411.11], EntityPig['Pig'/212, l='MpServer', x=-762.16, y=76.00, z=282.13], EntityPig['Pig'/213, l='MpServer', x=-757.16, y=75.00, z=279.84], EntityPig['Pig'/214, l='MpServer', x=-746.50, y=77.00, z=274.31], EntitySpitfireSkeleton['Spitfire Skeleton'/1725, l='MpServer', x=-751.50, y=20.00, z=404.50], EntityPig['Pig'/215, l='MpServer', x=-756.38, y=75.00, z=275.47], EntitySquid['Squid'/1423, l='MpServer', x=-883.50, y=61.00, z=297.50], EntityJumpingCreeper['Jumping Creeper'/89, l='MpServer', x=-895.00, y=33.00, z=414.50], EntityCow['Cow'/234, l='MpServer', x=-746.44, y=78.00, z=309.63], EntityCow['Cow'/232, l='MpServer', x=-748.56, y=78.00, z=294.63], EntityIcyEnderman['Icy Enderman'/231, l='MpServer', x=-746.69, y=29.00, z=290.84], EntityBat['Bat'/2174, l='MpServer', x=-838.35, y=17.00, z=377.33], EntityPig['Pig'/230, l='MpServer', x=-756.47, y=77.00, z=274.31], EntityBat['Bat'/2173, l='MpServer', x=-844.87, y=17.01, z=385.51], EntityBrutishZombie['Brutish Zombie'/115, l='MpServer', x=-864.09, y=28.00, z=354.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows Server 2012 (amd64) version 6.2
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 89016976 bytes (84 MB) / 518979584 bytes (494 MB) up to 518979584 bytes (494 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512m -Xincgc -XX:MaxPermSize=128m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 72 mods loaded, 72 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsCore{@VERSION@} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core] (malisiscore-1.7.10-0.10.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_LargeSign{2.0} [Large Sign] ([1.7.10-10.13.2.1230]Large Sign-2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ClothingCraft{1.2.1} [ClothingCraft] ([1.7.10] ClothingCraft 1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SC0_SpaceCore{0.7.12} [SpaceCore] ([1.7.10] SpaceCore 0.7.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SC0_UsefulPets{1.2.4} [Useful Pets] ([1.7.10] Useful Pets 1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	InvisibLights{2.2-6} [InvisibLights] ([1.7.10]InvisibLights-2.2-6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	heart{2.0.0} [Heart Health] ([MC1.7.X]Hearts-2.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	animalsPlus{1.2} [Animals+] (animalsPlus-1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2{rv1-stable-1} [Applied Energistics 2] (appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1062-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BossTools{1.1.3} [Boss Tools] (BossTools-1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cannibalism{1.0.2} [Cannibalism] (Cannibalism-1.0.2-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CleanView{1.7.10-v2} [CleanView] (CleanView-1.7.10-v2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.0B6} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B6-32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CosmeticArmor{1.0.5} [Cosmetic Armor] (CosmeticArmor-1.7.10-1.0.5.B8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	lootablebodies{1.3.2} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.3.2-backport.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	props{1.11} [Decocraft] (Decocraft-v1.11_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderIO{1.7.10-2.2.2.285} [Ender IO] (EnderIO-1.7.10-2.2.2.285.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraFood{0.6.0} [Extra Food] (ExtraFood-1.7.10-0.6.47.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	fairylights{0.6} [Fairy Lights] (fairylights-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FlatSigns{2.1.0.19} [Flat Signs] (FlatSigns-1.7.10-universal-2.1.0.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	fognerf{1.7.10-0.3} [Fog Nerf] (fognerf-1.7.10-0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	infiniteinvo{1.0.29} [InfiniteInvo] (InfiniteInvo-1.0.29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Pads{2.3.0} [JumpPad++] (JumpPad++_2.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LLadders{0.5.0} [Luppii's Ladders] (Ladders-0.5.0-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	malisisdoors{1.7.10-1.4.3} [Malisis' Doors] (malisisdoors-1.7.10-1.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MoarSigns{1.1.4} [MoarSigns] (MoarSigns-1.7.10-1.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	modularpots{1.7.10.14} [Modular Flower Pots] (ModularPots-1.7.10.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NaturalAbsorption{1.2.1} [Natural Absorption] (NaturalAbsorption-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-223.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-431.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PetBat{1.3.6} [Pet Bat] (PetBat-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	rafradek_wallpaint{1.5.4} [Wall Painter] (rafradek_wallpaint-1.5.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalExpansion{1.7.10R4.0.0B6} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B6-16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RedstoneArsenal{1.7.10R1.1.0B3} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0B3-8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.404.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	simplyjetpacks{1.3.2} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SolarFlux{1.7.10-0.4b} [Solar Flux] (SolarFlux-1.7.10-0.4b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpecialMobs{3.0.3} [Special Mobs] (SpecialMobs-1.7.10-3.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpiceOfLife{1.2.3} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SteelIndustries{1.7.10-0.5c} [Steel Industries] (SteelIndustries-1.7.10-0.5c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TooMuchTime{2.2.0} [TooMuchTime] (TooMuchTime-1.7.2-2.2.0.7-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Translocator{1.1.1.6} [Translocator] (Translocator-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Waila{1.5.8} [Waila] (Waila-1.5.8a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	zoommod{1.2} [zoommod] (ZoomMod-1.2_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	HungerOverhaul{1.7.10-beta.5.jenkins47} [Hunger Overhaul] (HungerOverhaul-1.7.10-beta.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: GeForce 8600 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Badcholo** [comment]
Super Epic Mod, I have changed the config to not use vanilla inventory and it's working so awsome. I'll keep you posted

**Comment by Funwayguy** [comment]
I believe this is fixed now
