### ISSUE TITLE
Getting an error (not crashing) after logging into SP/MP

### ISSUE THREAD

**Issue by diamondpumpkin** [Funwayguy/InfiniteInvo#24]
When I try to join a server or play on single player. I tend to get kicked off saying this connection has been terminated.

Pastebin error report: http://pastebin.com/NRSaWgBd

If you could fix this or tell me what mod it is causing this, that would be awesome. Thanks!

**Comment by Funwayguy** [comment]
Looks like I screwed up somewhere in the network handlers again. I'll fix it when I have have some free time between my studies.

**Comment by diamondpumpkin** [comment]
Cool, thanks!

**Comment by Funwayguy** [comment]
I've fixed this for the next update but I can't guarantee when that will be released as I have some other bugs I want to take care of first.
