### ISSUE TITLE
Bug: "Use Orbs" option doesn't work if your number of LEVELS is less than the number of orbs required.

### ISSUE THREAD

**Issue by Gaelan** [Funwayguy/InfiniteInvo#26]
I found a bug! I can code, but I can't/am to lazy to learn how to set this up in a Forge dev environment, so the best I can do is report it:

On [this line][bad-line], the server checks if the users has enough XP to unlock the next slot. However, it doesn't check if the cost is in levels or orbs, and therefore you need to HAVE a lot more XP then you actually need to use to buy a slot.

[bad-line]: https://github.com/Funwayguy/InfiniteInvo/blob/master/src/main/java/infiniteinvo/network/InvoPacket.java#L73

**Comment by Funwayguy** [comment]
Knew I missed a spot somewhere. Thanks for pointing that one out, should have it fixed soon as long as my studies don't get too hectic

**Comment by Funwayguy** [comment]
Update pushed out which should fix this
