### ISSUE TITLE
Ctrl shift click crash

### ISSUE THREAD

**Issue by Seiklus** [Funwayguy/InfiniteInvo#36]
http://paste.ee/p/kfzl7

Incompatibiltiy with Minecraft(?)

ctrl + Shift clicking on inventory to remove all "item" (Skyroot beds:aether) stacks crashes the game.
Note that i tested this with invtweaks patch on and off, and i even removed Invtweaks and the crash still happens (on a new world)

**Comment by Funwayguy** [comment]
The log provided isn't a crash log nor contains anything about the crash you described. Please post the proper crash log and then I can help you with your issue.
