### ISSUE TITLE
Vanilla Compatibility

### ISSUE THREAD

**Issue by devryb** [Funwayguy/InfiniteInvo#4]
Is it possible to disable this mod client side if the player attempts to login to a Vanilla server?
Normally all forge mods allow connecting to Vanilla but this one doesn't it gets an infinite loop error:

01.01 04:21:39 [Server] INFO devryb has left the hub!
01.01 04:21:39 [Disconnect] User devryb has disconnected, reason: Internal server error
01.01 04:21:39 [Multicraft] devryb ran command Message of the Day
01.01 04:21:39 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [hub.jar:git-Spigot-1649]
01.01 04:21:39 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [hub.jar:git-Spigot-1649]
01.01 04:21:39 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [hub.jar:git-Spigot-1649]
01.01 04:21:39 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [hub.jar:git-Spigot-1649]
01.01 04:21:39 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [hub.jar:git-Spigot-1649]
01.01 04:21:39 [Server] INFO at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [hub.jar:git-Spigot-1649]
01.01 04:21:39 [Server] INFO at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) ~[hub.jar:git-Spigot-1649]
01.01 04:21:39 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInCustomPayload.handle(PacketPlayInCustomPayload.java:51) ~[hub.jar:git-Spigot-1649]
01.01 04:21:39 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:39) ~[hub.jar:git-Spigot-1649]
01.01 04:21:39 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1964) ~[hub.jar:git-Spigot-1649]
01.01 04:21:39 [Server] INFO at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:419) ~[hub.jar:git-Spigot-1649]
01.01 04:21:39 [Server] INFO at org.bukkit.plugin.messaging.StandardMessenger.validateChannel(StandardMessenger.java:446) ~[hub.jar:git-Spigot-1649]
01.01 04:21:39 [Server] INFO org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 16 chars (attempted 18 - 'INFINITE_INVO_CHAN.

**Comment by Yorkforce** [comment]
Would also like the report this issue, its happening to every player that joins our network who has it installed (no other mods do this)

**Comment by Funwayguy** [comment]
This isn't actually a bug with client-server side actions. It appears to be a packet channel name limit which InfiniteInvo breaks. I'll fix it up now

**Comment by Funwayguy** [comment]
This is fixed now I believe
