### ISSUE TITLE
Changing dimension erases extra items

### ISSUE THREAD

**Issue by Xandaros** [Funwayguy/InfiniteInvo#40]
Going through the portal after defeating the ender dragon results in all items being deleted, apart from the first 27 items and the hotbar. (and armour, probably. didn't check)

**Comment by Funwayguy** [comment]
Confirmed this does happen and it is seriously bad. I'm working on fixing it now

**Comment by Mewtwoy** [comment]
Why dint i see this earlier? f**k!
guess i lost over 480 lots of items

**Comment by Funwayguy** [comment]
Yea sorry about that. I'm trying to fix this (4 failed dev builds with it still happening) but Forge isn't firing events at the right time to catch the items before they're erased. For the record this applies to every dimension teleportation (I'll change the title) not just the End.

PS: Try to not to use profanity in the issue tracker as frustrating as it is.

**Comment by Xandaros** [comment]
I am happily going back and forth between the nether and the overworld. Going _to_ the end works just as fine, as well, only coming back is causing this issue.

Using mystcraft linking books has been safe so far, as well. (I have not tried custom ages, though. I installed mystcraft because of this problem.)

**Comment by Funwayguy** [comment]
Odd, I have the issue even when going back and forth from the nether. Must have been something I touched while trying to fix the original issue.

**Comment by Funwayguy** [comment]
Well this just gets even more interesting. Turns out it wasn't creative mode specifically doing it. ANY dimension changing after completing the end results in erased items. You'll just have to re-log to fix it after you leave the End

**Comment by Funwayguy** [comment]
Well I've fixed it for survival mode but Creative is still very broken
