### ISSUE TITLE
Skyforge2 modpack issue

### ISSUE THREAD

**Issue by GOzziCraft** [Funwayguy/InfiniteInvo#49]
Hi, i have skyforge 2 modpack from the ATLauncher installed.
With the modpack is comming inventoryTweaks as well.
If i install both mods the auto-refill from InventoryTweaks is not working anymore. Is there a way to fix this?

**Comment by Funwayguy** [comment]
Not from my side no. You'll need to contact the ITweaks dev about their inventory handling.

I should also point out there are other notable issues such as sorting with extra or locked slots not working as expected. Most of these is not game breaking, just a little frustrating.

**Comment by GOzziCraft** [comment]
ok, thanks for letting me know, i will cntact the guys from InventoryTweaks
then. btw your mod is awesome.
