### ISSUE TITLE
BetterChests Bug

### ISSUE THREAD

**Issue by yosomith** [Funwayguy/InfiniteInvo#6]
There is a bug with this mod and BetterChests where opening a Better Chest does weird things with your inventory, it seems like it dupes but it doesn't, it's just a display bug but it does make using the two mods together very difficult.

This was using the latest version of both InfiniteInvo (1.0.25) and BetterChests (1.1.1.8)

**Comment by Funwayguy** [comment]
Can you provide one or more screenshots of this? I just need an idea of what is actually happening to the inventory

**Comment by yosomith** [comment]
Sure, here is my inventory before opening the chest: http://i.imgur.com/AETHbRT.png

Here is the chest open: http://i.imgur.com/rdXQaKg.png

And last the result afterwards: http://i.imgur.com/zdTeptR.png

Picking up any item reverts the inventory back to the first pick so no items are lost or duplicated.

**Comment by Funwayguy** [comment]
Well it turns out this bug was actually already fixed in a version newer than the one currently in SF2. Also this is actually related in the weird way Inventory Tweaks is handling the new size of the inventory and the locked slots, so not something I can fix.
