### ISSUE TITLE
Lowering Max Inventory Slots has no Effect

### ISSUE THREAD

**Issue by blueyu2** [Funwayguy/InfiniteInvo#8]
In the config I set both "No. Start Unlocked" and "Max Invo Size" to 0 and I am still able to put items in my inventory. I am using Forge 10.13.2.1286 and InfiniteInvo 1.0.25.
![2015-01-22_21 03 46](https://cloud.githubusercontent.com/assets/6446871/5869202/d13e007e-a27a-11e4-9863-c6fbefeb39c2.png)

**Comment by Funwayguy** [comment]
*Facepalm*... looks like I dun goofed a bit of code. I'll fix that up soon

**Comment by Funwayguy** [comment]
Fixed for the next update.
